# Generated by Django 2.2.4 on 2019-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190821_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.BooleanField(),
        ),
    ]
